In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df = pd.read_csv('/MachineLearning/assignment/dataset/bankloan.csv')
df=df.drop(columns=['ID','ZIP.Code'],axis=1) 
df

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0      25           1      49       4    1.6          1         0   
1      45          19      34       3    1.5          1         0   
2      39          15      11       1    1.0          1         0   
3      35           9     100       1    2.7          2         0   
4      35           8      45       4    1.0          2         0   
...   ...         ...     ...     ...    ...        ...       ...   
4995   29           3      40       1    1.9          3         0   
4996   30           4      15       4    0.4          1        85   
4997   63          39      24       2    0.3          3         0   
4998   65          40      49       3    0.5          2         0   
4999   28           4      83       3    0.8          1         0   

      Personal.Loan  Securities.Account  CD.Account  Online  CreditCard  
0                 0                   1           0       0           0  
1                 0                   1           0       0           0  
2                 0                   0           0       0           0  
3                 0                   0           0       0           0  
4                 0                   0           0       0           1  
...             ...                 ...         ...     ...         ...  
4995              0                   0           0       1           0  
4996              0                   0           0       1           0  
4997              0                   0           0       0           0  
4998              0                   0           0       1           0  
4999              0                   0           0       1           1  

[5000 rows x 12 columns]

In [5]:
df.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal.Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities.Account  CD.Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [6]:
X = df.drop(columns=["Personal.Loan"])  # Features
y = df["Personal.Loan"]  # Target variable

In [10]:
X.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0   25           1      49       4    1.6          1         0   
1   45          19      34       3    1.5          1         0   
2   39          15      11       1    1.0          1         0   
3   35           9     100       1    2.7          2         0   
4   35           8      45       4    1.0          2         0   

   Securities.Account  CD.Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [11]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Personal.Loan, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le_x=LabelEncoder()
x = X.apply(le_x.fit_transform)

In [16]:
X

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0      25           1      49       4    1.6          1         0   
1      45          19      34       3    1.5          1         0   
2      39          15      11       1    1.0          1         0   
3      35           9     100       1    2.7          2         0   
4      35           8      45       4    1.0          2         0   
...   ...         ...     ...     ...    ...        ...       ...   
4995   29           3      40       1    1.9          3         0   
4996   30           4      15       4    0.4          1        85   
4997   63          39      24       2    0.3          3         0   
4998   65          40      49       3    0.5          2         0   
4999   28           4      83       3    0.8          1         0   

      Securities.Account  CD.Account  Online  CreditCard  
0                      1           0       0           0  
1                      1           0       0           0  
2                      0           0       0           0  
3                      0           0       0           0  
4                      0           0       0           1  
...                  ...         ...     ...         ...  
4995                   0           0       1           0  
4996                   0           0       1           0  
4997                   0           0       0           0  
4998                   0           0       1           0  
4999                   0           0       1           1  

[5000 rows x 11 columns]

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.30, random_state=1)

In [18]:
xtrain

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
1334   47          22      35       2    1.3          1         0   
4768   38          14      39       1    2.0          2         0   
65     59          35     131       1    3.8          1         0   
177    29           3      65       4    1.8          2       244   
4489   39          13      21       3    0.2          2         0   
...   ...         ...     ...     ...    ...        ...       ...   
2895   60          36      39       4    1.3          2       140   
2763   55          31      13       4    0.7          1         0   
905    46          22      28       1    1.0          1        84   
3980   46          22      89       4    1.4          2         0   
235    38           8      71       4    1.8          3         0   

      Securities.Account  CD.Account  Online  CreditCard  
1334                   0           0       1           0  
4768                   0           0       1           0  
65                     0           0       1           1  
177                    0           0       0           0  
4489                   0           0       1           0  
...                  ...         ...     ...         ...  
2895                   0           0       1           0  
2763                   0           0       1           0  
905                    0           0       1           1  
3980                   0           0       1           0  
235                    0           0       1           0  

[3500 rows x 11 columns]

In [19]:
xtest

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
2764   31           5      84       1   2.90          3       105   
4767   35           9      45       3   0.90          1       101   
3814   34           9      35       3   1.30          1         0   
3499   49          23     114       1   0.30          1       286   
2735   36          12      70       3   2.60          2       165   
...   ...         ...     ...     ...    ...        ...       ...   
4140   63          38      32       1   1.50          2         0   
3969   38          11      75       3   2.33          2         0   
2535   50          25      21       2   0.70          3       129   
1361   50          26      38       4   0.90          2         0   
1458   51          25      33       1   1.40          3         0   

      Securities.Account  CD.Account  Online  CreditCard  
2764                   0           0       0           1  
4767                   1           0       0           0  
3814                   0           0       0           0  
3499                   0           0       1           0  
2735                   0           0       1           0  
...                  ...         ...     ...         ...  
4140                   0           0       0           0  
3969                   0           0       1           0  
2535                   0           0       0           0  
1361                   0           0       1           0  
1458                   0           0       1           1  

[1500 rows x 11 columns]

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
dect = DecisionTreeClassifier()

In [22]:
dect.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [23]:
dect.score(xtest, ytest)

0.9786666666666667

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
result = cross_val_score(DecisionTreeClassifier(), X, y,cv=5)
result

array([0.982, 0.977, 0.984, 0.982, 0.982])

In [26]:
result.mean()

np.float64(0.9814)

In [27]:
from sklearn.linear_model import LogisticRegression
result = cross_val_score(LogisticRegression(), X, y,cv=5)
result

D:\MachineLearning\pyvenvmain\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\MachineLearning\pyvenvmain\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

array([0.946, 0.943, 0.948, 0.95 , 0.955])

In [28]:
result.mean()

np.float64(0.9484)

In [29]:
y_predict = dect.predict(xtest)
y_predict

array([0, 0, 0, ..., 0, 0, 0], shape=(1500,))

In [30]:
from sklearn.metrics import classification_report, confusion_matrix

In [31]:
print(classification_report(ytest,y_predict))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1351
           1       0.89      0.89      0.89       149

    accuracy                           0.98      1500
   macro avg       0.94      0.94      0.94      1500
weighted avg       0.98      0.98      0.98      1500

